authentication/urls.py
'''Defines url patterns for authentication'''
from django.urls import path
from . import views

app_name = "authentication"
urlpatterns = [
    path('student-signup/', views.StudentSignUp.as_view(), name='student_signup'),
    path('teacher-signup/', views.TeacherSignUp.as_view(), name='teacher_signup'),
]

main_quiz/urls.py
"""Defines URL patterns for main_quiz"""

from django.urls import path
from . import views

#Distiguish this URL from other URL's from other Django apps
app_name = 'main_quiz'
urlpatterns = [
    #Defining the URL pattern used to access the homepage, once this URL has been entered, the fucntion index() from the file views will be called. Name attribute allows us to refrence this URL in other sections of code.
    path('', views.index, name='index'),
    path('practice-mode/', views.practice_mode, name='practice_mode'),
    # Detail page for a single times table.
    path('start-quiz/<int:times_table_id>/', views.times_table, name='start_quiz'),
    path('my-question-overview/', views.question_overview, name='question_overview'),
    path('leaderboard/<int:times_table_id>/', views.leaderboard, name='leaderboard'),
    path('all-leaderboards/', views.leaderboards, name='all_leaderboards'),
    path('teacher-overview/', views.teacher_overview, name='teacher_overview'),
    path('create-classroom/', views.create_classroom, name='create_classroom'),
    path('update-classroom/<int:id>/', views.update_classroom, name='update_classroom'),
    path('delete-classroom/<int:id>/', views.delete_classroom, name='delete_classroom'),
    path('classroom-overview/<int:id>/', views.classroom_overview, name='classroom_overview'),
    path('student-overview/', views.student_overview, name='student_overview'),
    path('quiz-mode-preview/', views.quiz_mode_preview, name='quiz_mode_preview'),
    path('practice-mode-preview/', views.practice_mode_preview, name='practice_mode_preview'),
    path('join-classroom/', views.join_classroom, name='join_classroom'),
]

mcq_quiz/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('allauth.urls')),
    path('auth/', include('authentication.urls')),
    path('', include('main_quiz.urls')),
    
]

templates/all_leaderboards.html
{% extends "base.html" %}
{% block content%}

<h1>multipleChoice Multiplication - Class Leaderboards For Each Times Table</h1>

<ul>
    {% for multiple in times_tables %}
    <li><a href="{% url 'main_quiz:leaderboard' multiple %}">{{multiple}} Times Table Leaderboard</a></li>
    {% endfor %}
</ul>

{% endblock %}

templates/base.html
{% load static %}
<script type="text/javascript" src="{% static 'js/htmx.min.js '%}"></script>
<p>
    <!--Provide a link for students to access the homepage-->
    <a href="{% url 'main_quiz:index' %}">Homepage</a> -
    <!--If user is already logged in, display the name of the user-->
    {% if user.is_authenticated %}
        Hello, {{ user.first_name }}.
        <!--If users are authenticated, give them an option in the nav-bar to log out of the website.-->
        <a href="{% url 'main_quiz:practice_mode' %}">Practice Mode</a> -
        <a href="{% url 'main_quiz:quiz_mode_preview' %}">Quiz Mode</a> - 
        <a href="{% url 'main_quiz:question_overview' %}">My Question Overview</a> -
        <a href="{% url 'main_quiz:teacher_overview' %}">Teacher Overview</a> -
        <a href="{% url 'main_quiz:all_leaderboards' %}">Leaderboards</a> -
        <a href="{% url 'main_quiz:join_classroom' %}">Join Classroom</a> - 
        <a href="#" onclick="document.getElementById('logout-form').submit()">Logout</a>
        <form method="post" action="{% url 'account_logout' %}" id="logout-form">
          {% csrf_token %}

        </form>
    <!--Otherwise, if they are not authenticated, display a link allwoing the user to log in to their existing account-->
    {% else %}
      <a href="{% url 'authentication:student_signup' %}">Student Sign Up</a> -
      <a href="{% url 'authentication:teacher_signup' %}">Teacher Sign Up</a> -
      <a href="{% url 'account_login' %}">Log In</a> 
    {% endif %}
</p>

{% block content %}{% endblock content %}

templates/classroom_overview.html
{% extends 'base.html' %}

{% block content %}
    <h1>{{ classroom.classroom_name }} Classroom</h1>
    <p>Classroom code: {{ classroom.classroom_code }}</p>
    {% if students %}
        <table>
            <thead>
                <tr>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>Email</th>
                    <th>Oveerview</th>
                </tr>
            </thead>
            <tbody>
                {% for student in students %}
                    <tr>
                        <td>{{ student.user.first_name }}</td>
                        <td>{{ student.user.last_name }}</td>
                        <td>{{ student.user.email }}</td>
                        <td><a href="#">View Student Overview</a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>No students to display for classroom overview. </p>
        <p>Send an invite link to your students so they can join this class</p>
    {% endif %}
{% endblock content %}

templates/delete_classroom.html
{% extends "base.html" %}

{% block content %}

<h1>Delete classroom</h1>
<form method="post" action="{% url 'main_quiz:delete_classroom' classroom.id %}">
  {% csrf_token %}
    <p>Are you sure you want to delete {{ classroom.classroom_name}}?</p>
    <a href="{% url 'main_quiz:teacher_overview' %}">Cancel</a>
  <button type="submit">Delete classroom</button>
</form>


{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block content %}
<!--Basic layout for homepage, includes title and brief description of what the website will help students do-->
    <h1>multipleChoice Multiplication</h1>
    <p>The place where YOU can improve on your mulitplication skills!</p>
{% endblock content %}

templates/join_classroom.html
{% extends 'base.html' %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Join Classroom">
</form>
{% endblock content %}

templates/join_classroom_results.html
{% extends 'base.html' %}

{% block content %}
{% if successfully_joined %}
    <p>You have successfully joined {{ classroom_name }}</p>
{% else %}
    <p>Not able to find a classroom with this code. Please check the code you entered, and then <a href="{% url 'main_quiz:join_classroom'%}">try again</a>.</p>
{% endif %}
{% endblock content %}

templates/practice_mode.html
{% extends "base.html" %}

{% block content %}

<h1>multipleChoice Multiplication - Practice Mode</h1>

<ul>
    {% for multiple in times_tables %}
    <li><a href="{% url 'main_quiz:start_quiz' multiple.times_table%}">Practice {{multiple.times_table}} times table</a></li>
    {% endfor %}
</ul>


{% endblock %}

templates/practice_mode_preview.html
{% extends 'base.html' %}

{% block content %}

    <h1>Quiz Mode</h1>
    <p>Test your knowledge by choosing a times table!</p>

    {% if times_tables %}
        <p>Click here to practice your:</p>
        {% for times_table in times_tables %} 
            <p><a href="{% url 'main_quiz:start_quiz' times_table.id %}">{{times_table}} times table</a></p>
        {% endfor %}
    {% else %}
        <p>Sorry, there currently aren't any times tables in our system. We are doing our best right now to resolve this issue.</p>
    {% endif %}

{% endblock content %}

templates/question_overview.html
{% extends "base.html" %}
{% block content%}

<style>
table, th, td {
    border:1px solid black;
  }
  </style>

<h3>Question overview for {{ user.first_name }} {{ user.last_name }}</h3>
<table>
    <tr>
        <th>Times Table</th>
        <th>Average Percentage</th>
    </tr>
    {% for times_table, average_score in overview.items %}
        <tr>
            <td><a href="{% url 'main_quiz:start_quiz' times_table.times_table %}">{{ times_table.times_table }}</a></td>
            {% if average_score %}
                <td>{{ average_score }}%</td>
            {% else %}
                <td>-</td>
            {% endif %}
        </tr>
    {% endfor %}
    
</table>
{% endblock content %}

templates/quiz_mode_preview.html
{% extends 'base.html' %}

{% block content %}

<h1>Practice Mode</h1>
<p>Practice on your weakest topics!</p>

{% if weakest_times_table %}
    <p>Hi {{ user.first_name }}, your weakest times table is your {{weakest_times_table.times_table }} times table.</p>

    <p><a href="{% url 'main_quiz:start_quiz' weakest_times_table.times_table %}">Click here to practice your {{weakest_times_table.times_table }} times table.</a></p>
{% else %}
    <p>You currently don't have a weakest times table. Head over to the <a href="{% url 'main_quiz:practice_mode_preview' %}">quiz section</a> to be quizzed on new times tables.</p>
{% endif %}

{% endblock content %}

templates/start_quiz.html
{% extends 'base.html' %}

{% block content %}
    <h1>{{ times_table }} Times Table Quiz</h1>
    <form action="" method="post">
        {% csrf_token %}
        {% for question in questions %}
            <p>Question: {{ question.question_text }}</p>
            <div>
                <div>
                    <input type="radio" name="{{question}}" value="{{question.options.0}}" id="option_0" required>
                    <label for="option_0">{{question.options.0 }}</label>
                </div>
                <div>
                    <input type="radio" name="{{question}}" value="{{question.options.1}}" id="option_1" required>
                    <label for="option_1">{{question.options.1 }}</label>
                </div>
                <div>
                    <input type="radio" name="{{question}}" value="{{question.options.2}}" id="option_2" required>
                    <label for="option_2">{{question.options.2 }}</label>
                </div>
                <div>
                    <input type="radio" name="{{question}}" value="{{question.options.3}}" id="option_3" required>
                    <label for="option_3">{{question.options.3 }}</label>
                </div>
            </div>
        {% endfor %}
        <button type="submit">Submit</button>
    </form>

{% endblock content %}

templates/teacher_overview.html
{% extends 'base.html' %}

{% block content %}
    <h1>Welcome, {{ teacher_profile.teacher_name }}!</h1>
    {% if classrooms %}
        <h2>Here are your current classrooms:</h2>
        {% for classroom in classrooms %}
            <div>
                <a href="{% url 'main_quiz:classroom_overview' classroom.id %}">{{ classroom.classroom_name }}</a> - <a href="{% url 'main_quiz:update_classroom' classroom.id %}">Update classroom name</a> - <a href="{% url 'main_quiz:delete_classroom' classroom.id %}">Delete classroom</a>
            </div>

        {% endfor %}        
    {% else %}
        <p>There are no classrooms. Click below to create a classroom.</p>
    {% endif %}
    <br>
    <div>
        <a href="{% url 'main_quiz:create_classroom' %}">Create classroom</a>
    </div>

{% endblock content %}

templates/update_classroom.html
{% extends "base.html" %}

{% block content %}

<h1>Update classroom</h1>
<form method="post" action="{% url 'main_quiz:update_classroom' classroom.id %}">
  {% csrf_token %}
  {{ form.as_p }}

  <button type="submit">Update classroom</button>
</form>


{% endblock %}